server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # User Service
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**,/api/user/**,/api/admin/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: USER-SERVICE
                    fallbackUri: forward:/userServiceFallBack

            # Product Service
            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/createProduct,/api/getAllProducts,/api/product/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: PRODUCT-SERVICE
                    fallbackUri: forward:/productServiceFallBack

            # Order Service
            - id: ORDER-SERVICE
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: ORDER-SERVICE
                    fallbackUri: forward:/orderServiceFallBack

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      USER-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      PRODUCT-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      ORDER-SERVICE:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  timelimiter:
    instances:
      USER-SERVICE:
        timeoutDuration: 4s

      PRODUCT-SERVICE:
        timeoutDuration: 4s

      ORDER-SERVICE:
        timeoutDuration: 4s

jwt:
  secret: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yQ29tbWVyY2VIdWJKV1QxMjM0NTY3ODkwMTIzNDU2