
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere_user_db
spring.datasource.username=root
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:changeme}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=${JWT_SECRET:changeme}
jwt.expiration=86400000